
development:
  adapter: postgresql
  encoding: unicode
  database: YKdotcom_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: YKdotcom_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: YKdotcom_production
  pool: 5
